### PR TITLE
Cutify

### LINKED ISSUE #24: Cannot play two audio files simultaneously
Setup a QML Component with two `Audio` qml type, try to play them in parallel, One of the stream is stopped.

### LINKED ISSUE #29: Music doesn't stop when clossing music app on non-hybris devices
Steps to reproduce the bug:
Open music-player-->Play music-->Close the music app.
The music doesn't stops.

### PR DESCRIPTION
**Pull request by mardy**
This is now ready for review. I've tested a few use cases, and everything seems to work fine. Playing remote media also works.

I've removed the unit tests, which were not testing much anyway, and replaced them with functional tests where the whole media-hub-server component is run in a standalone D-Bus session where all dependent services (like powerd, the power indicator, telepathy) are mocked.

Fixes: https://github.com/ubports/media-hub/issues/29
Fixes: https://github.com/ubports/media-hub/issues/24

### CODE REVIEW

**Comment by cibersheep** [comment]
[media-hub.log](https://github.com/ubports/media-hub/files/6475844/media-hub.log)
Installed on E5 dev channel
- Play a song from Music
- Take a screenshot

Expected:
- Music Volume decreases
- Screenshot notification sound plays
- Music volume returns to previous levels

Experienced:
- Music stops playing
- Screenshot notification doesn't sound
- Trying to start music from Sound indicator plays screenshot notification (if tapped several times)
- No info from song is displayed anymore
- Playing song from Music app starts song

[bustle.log](https://github.com/ubports/media-hub/files/6475807/bustle.log)

[media-hub.log](https://github.com/ubports/media-hub/files/6475846/media-hub.log)

**Comment by cibersheep** [comment]
- Play a list of songs
- Tap on next or previous (from Music app or from Sound indicator)

Expected
- Next or previous song plays

Experienced
- Next or previous song is loaded
- Song stops

[bustle.log](https://github.com/ubports/media-hub/files/6475874/bustle.log)

**Comment by cibersheep** [comment]
I tested [Animal Farm](https://open-store.io/app/animal-farm.bhdouglass)
- Press each animal and let it play until the end
- Press each animal and press the next one before previous animal stops playing

Expected:
- Animal sounds plays until the end
- Animal sound pauses if another animal is pressed

Experienced:
- Cat, dog and sheep doesn't play
- Goat, elephant and cow plays partly (they paused of another animal is pressed before they interrupt by itself)

[bustle.log](https://github.com/ubports/media-hub/files/6475946/bustle.log)

**Comment by mardy** [comment]
Thanks @cibersheep , I think I now fixed all the issues. AnimalFarm will now not stop the current sound (that is, I also fixed https://github.com/ubports/media-hub/issues/24 in the process), and I filed https://gitlab.com/bhdouglass/animal-farm/-/issues/4 in case Brian doesn't like the new behaviour.

**Comment by cibersheep** [comment]
All three issues are fixed with today's build. Thanks
I need to test it on Arale and receive a call

**Comment by cibersheep** [comment]
Tested on Arale.
Works: while music playing
- notifications sounds (music attenuates)
- received a call (music stops)
- selecting a new song works
- indicator tracking controls works

Checked
- Microphone works
- headphones works (audio and mic)
- bluetooth audio works

Taking a screenshot
- sound works
- music if plating, keep playing

File: debian/rules [hunk 1]
```diff
@@ -20,6 +20,8 @@ major=$(shell echo $(full_version) | cut -d'.' -f1)
 minor=$(shell echo $(full_version) | cut -d'.' -f2)
 patch=$(shell echo $(full_version) | cut -d'.' -f3)
 
+# CONFIGURE_FLAGS += -DCMAKE_BUILD_TYPE=Coverage
```
Comment (UniversalSuperBox) [inline debian/rules]: Any reason why we're adding commented code to the build system?

File: src/core/media/hybris_recorder_observer.cpp [hunk 2]
```diff
@@ -24,20 +24,12 @@ namespace media = core::ubuntu::media;
...
-    struct Holder
-    {
-        std::weak_ptr<media::HybrisRecorderObserver::Private> wp;
-    };
-
     // The fringe that we hand over to hybris.
     static void on_media_recording_state_changed(bool started, void* context)
     {
-        if (auto holder = static_cast<Holder*>(context))
+        if (auto thiz = static_cast<HybrisRecorderObserver*>(context))
```
Comment (UniversalSuperBox) [inline src/core/media/hybris_recorder_observer.cpp:30]: Something appears to be broken in the hybris_recorder_observer or somewhere else that controls media recording and screen off. If I:

1. Open Camera-app
2. Start recording a video
3. Close camera-app without stopping recording

It is expected that the screen will time out normally after the camera-app closes. However, it does not. Instead, it stays on forever.

Tested on Nexus 4 for failure case. On Nexus 5 with old media-hub, this test passes.

File: src/core/media/power/state_controller.h [hunk 3]
```diff
@@ -33,14 +30,7 @@ namespace media
...
 {
-// Enumerates all known power states of a display.
-enum class DisplayState
-{
-    // The display is off.
-    off = 0,
-    // The display is on.
-    on = 1
-};
+Q_NAMESPACE
```
Comment (UniversalSuperBox) [inline src/core/media/power/state_controller.h:33]: Another test related to display state has failed. However, this test also fails on the old media-hub and is not required to be fixed for merging this PR.

If I:

1. Open the Gallery
2. Tap a video for playback
3. Tap the Play button so the media-player app starts
4. Lock the screen before the media-player app loads

After a few seconds, the screen turns back on and video playback begins behind the lock screen.

File: src/core/media/mpris/media_player2.cpp [hunk 4]
```diff
@@ -0,0 +1,367 @@
...
+            m_propertyNotifier.notify({
+                "CanPlay", "CanPause", "CanSeek",
+                "CanGoPrevious", "CanGoNext",
+            });
+        });
+        QObject::connect(impl, &PlayerImplementation::playbackStatusChanged,
+                         this, [this]() {
+            m_propertyNotifier.notify({ "PlaybackStatus" });
+        });
+        QObject::connect(impl, &PlayerImplementation::metadataForCurrentTrackChanged,
```
Comment (UniversalSuperBox) [inline src/core/media/mpris/media_player2.cpp:244]: It is worth noting that these changes *did not* fix https://github.com/ubports/ubuntu-touch/issues/979 or https://github.com/ubports/ubuntu-touch/issues/1415. It is not expected that these were fixed from your description, but I wanted to log the results here.

Additionally, test 6 of "Test Basic TrackList Navigation" fails if Podbird is allowed to change tracks while it is suspended. It is possible to cause media-hub to play back two tracks at once in this case. However, it is the same issue as the others in this comment.

File: src/core/media/server/server.cpp [hunk 5]
```diff
@@ -16,55 +16,49 @@
  * Authored by: Jim Hodapp <jim.hodapp@canonical.com>
  */
 
-#include <core/media/service.h>
-#include <core/media/player.h>
-#include <core/media/track_list.h>
+#include "logging.h"
```
Comment (UniversalSuperBox) [inline src/core/media/server/server.cpp:19]: I've managed to cause the media-hub service to apparently lock up and be unable to play any remote media from Podbird. Unfortunately, I'm not sure how to reproduce it. I've captured a log of a long test session leading up to the error, but it may not be terribly helpful:

https://paste.ubuntu.com/p/3V3VQd7MNV/

Either way, the problem is that podbird is unable to play the podcast that it has queued up. The podcast is a network resource and it appears that media-hub is sending BufferingCompleted before immediately pausing playback. Playback cannot be resumed.

I was able to get it out of this state by playing a track from Podbird that was saved locally, then attempting to play the remote content again. https://paste.ubuntu.com/p/gbjKvTpfMM/

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
How you managed a +6477-13775 PR without many regressions from the known test plan is quite amazing.

However, I did find a few things wrong with the new implementation when testing against https://wiki.ubuntu.com/Process/Merges/TestPlan/media-hub. I've commented them here. Note that the comment locations are mostly not related to the code they point to. I just picked something that looked mostly correct.

File: debian/rules (hunk 1 above)
Comment (mardy) [reply debian/rules]: Yes, this is a flag that we don't want to use in production, because it makes the code bigger and slower, and it would make it produce coverage stats on every run. But it's still a flag that I find useful as a developer, so having it here in the debian/rules file makes it easier for me to enable it when needed.

However, a better way would be to make the flag conditional on the `DEB_BUILD_OPTIONS` variable. I'll change this.

File: src/core/media/hybris_recorder_observer.cpp (hunk 2 above)
Comment (mardy) [reply src/core/media/hybris_recorder_observer.cpp:30]: Yes, I've now tried it and I verified that *sometimes* the callback is not invoked. However, I doubt that this is due to my changes, since I added some debugging messages and verified that it's the platform API who is not invoking the callback. So, I suspect that the same issue must have been present even in the old implementation, and that you were just lucky to not reproduce it there :-)

File: src/core/media/power/state_controller.h (hunk 3 above)
Comment (mardy) [reply src/core/media/power/state_controller.h:33]: I created a bug for this, let's tackle it separately: https://github.com/ubports/media-hub/issues/30

File: src/core/media/mpris/media_player2.cpp (hunk 4 above)
Comment (mardy) [reply src/core/media/mpris/media_player2.cpp:244]: I see, but I'd rather address these issues separately. This has mostly been a rewrite, and I've tried hard to preserve the logic in the tracklist code even though I found it weird and overcomplicated. Since it's not a regression, I'd leave it for later.

File: src/core/media/server/server.cpp (hunk 5 above)
Comment (mardy) [reply src/core/media/server/server.cpp:19]: It's interesting, from line `9680` and following of your logs, it appears that the streamer playbin is encountering a `GST_RESOURCE_ERROR_FAILED` error even when playing local media. Are all the media files (like "Rozen - Children of Termina - 10 Moon's Tears (Astral Observatory)") playing in the old media-hub?

About the pausing: I wonder if it's the media-hub pausing itself, or if it's rather a command coming from the client (library). Could you please reproduce this again while running `busctl --user monitor core.ubuntu.media.Service`? That will show who is calling what :-)

Comment (mardy) [reply src/core/media/server/server.cpp:19]: I now added a commit to print the error message coming from gstreamer -- that should let us understand what was going wrong with those `GST_RESOURCE_ERROR_FAILED` errors.

File: debian/rules (hunk 1 above)
Comment (mardy) [reply debian/rules]: Done!

File: src/core/media/server/server.cpp (hunk 5 above)
Comment (UniversalSuperBox) [reply src/core/media/server/server.cpp:19]: Unfortunately I haven't been able to reproduce the exact issue so far. But I've got a script logging everything now, so hopefully we'll come across the culprit.

I have managed to find a similar, possibly related situation where playing the playlist then switching back and forth between positions in quick succession causes the player to pause but not resume.

[automatic-pause.txt](https://github.com/ubports/media-hub/files/6542600/automatic-pause.txt)

However, when this occurs, the indicator shows no media information, but Play and Skip Back are active. This might be related to https://github.com/ubports/ubuntu-touch/issues/979 and https://github.com/ubports/ubuntu-touch/issues/1415 instead.

Since I haven't been able to reproduce the problem, we might need to ignore it and hope for a better reproduction case later.

Comment (mardy) [reply src/core/media/server/server.cpp:19]: I don't think I reproduced the same issue you had, but it might be related: remote mp3 files I added to Podbird would not be recognized as `audio/mp3`, but rather as `application/octet-stream`. So, the `isAudioSource` was set to false, and qtubuntu-media would silently ignore the request to play these files.

I now added a commit (mostly taken from the old https://github.com/ubports/media-hub/pull/22) which obtains the media type from the gstreamer playbin.

Comment (UniversalSuperBox) [reply src/core/media/server/server.cpp:19]: I think that the original issue of this thread is the one you found and fixed. The "Back and Forward stress test" is still a mystery.

**Comment by lduboeuf** [comment]
awesome work. how to test for remote media ?

**Comment by lduboeuf** [comment]
Confirmed it fix #24 :)

**Comment by mardy** [comment]
> awesome work. how to test for remote media ?

You could try MiTubo; [here's a very old click](http://mardy.it/archivos/tmp/it.mardy.mitubo_0.1-0_armhf.click), let me know if you need arm64. I'll upload it to the store after the new media-hub gets released into some OTA.
Or, if you'd like to see the latest version, you can also build it yourself with clickable from [here](https://gitlab.com/mardy/mitubo).

**Comment by lduboeuf** [comment]
@mardy , humm , had no luck to build mitubo project with clickable version 6.24.1
```
WARNING: Error setting up Qt for '/usr/bin/qmake': Cannot extract the mkspecs directory.
ERROR: /home/lduboeuf/dev/perso/ubuntutouch/mitubo/mitubo.qbs:12:5 Error while handling product 'MiTubo':
/usr/share/qbs/imports/qbs/base/QtApplication.qbs:32:5 Dependency 'Qt.core' not found for product 'MiTubo'.
/usr/share/qbs/imports/qbs/base/QtGuiApplication.qbs:32:5 Dependency 'Qt.gui' not found for product 'MiTubo'.
/home/lduboeuf/dev/perso/ubuntutouch/mitubo/mitubo.qbs:69:9 Dependency 'Qt.core' not found for product 'MiTubo'.
/home/lduboeuf/dev/perso/ubuntutouch/mitubo/mitubo.qbs:70:9 Dependency 'Qt.quick' not found for product 'MiTubo'.
/home/lduboeuf/dev/perso/ubuntutouch/mitubo/mitubo.qbs:71:9 Dependency 'Qt.quickcontrols2' not found for product 'MiTubo'.
/home/lduboeuf/dev/perso/ubuntutouch/mitubo/mitubo.qbs:72:9 Dependency 'Qt.svg' not found for product 'MiTubo'.

**Comment by mardy** [comment]
> @mardy , humm , had no luck to build mitubo project with clickable version 6.24.1
[...]

I'll investigate why this happens. Meanwhile, please use `v6.23.3`, which works.

**Comment by lduboeuf** [comment]
@mardy well, same with 6.23.3, also the link provided for the click does not work here (http://mardy.it/archivos/tmp/it.mardy.mitubo_0.1-0_armhf.click)

**Comment by lduboeuf** [comment]
don't know if related but audio recording and playback doesn't work on messaging app:

Recording:
```
** (messaging-app:11017): CRITICAL **: gst_audio_format_from_string: assertion 'format != NULL' failed
ALSA lib conf.c:3814:(snd_config_update_r) cannot access file /usr/share/alsa/alsa.conf
[PERFORMANCE]: Last frame took 37 ms to render.

....

setMedia() media:  QUrl("file:///home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audioElXUfy.ogg")
virtual QMediaPlayer::MediaStatus AalMediaPlayerControl::mediaStatus() const 

Setting media to:  QUrl("file:///home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audioElXUfy.ogg")
Failed to set media  QUrl("file:///home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audioElXUfy.ogg") :  org.freedesktop.DBus.Error.UnknownObject: No such object path '/core/ubuntu/media/Service/sessions/0'


```

PlayBack:
```
void AalMediaPlayerService::play()
Failed to check if source is video:  org.freedesktop.DBus.Error.UnknownObject: No such object path '/core/ubuntu/media/Service/sessions/0'
Failed to get current playback position:  org.freedesktop.DBus.Error.UnknownObject: No such object path '/core/ubuntu/media/Service/sessions/0'

**Comment by mardy** [comment]
> don't know if related but audio recording and playback doesn't work on messaging app:
[...]

In both cases, it looks like media-hub is not running (it might have crashed, maybe?). Can you please reproduce it while collecting the bustle logs (`busctl --user monitor  core.ubuntu.media.Service`)?

**Comment by lduboeuf** [comment]
@mardy here is some logs:

Recording audio:
```
‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=2
  Sender=org.freedesktop.DBus  Destination=:1.178  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.178";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=24
  Sender=:1.175  Destination=core.ubuntu.media.Service  Path=/core/ubuntu/media/Service/sessions/0  Interface=org.mpris.MediaPlayer2.Player  Member=Stop
  UniqueName=:1.175
  MESSAGE "" {
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=51  ReplyCookie=24
  Sender=:1.176  Destination=:1.175
  ErrorName=org.freedesktop.DBus.Error.UnknownObject  ErrorMessage="No such object path '/core/ubuntu/media/Service/sessions/0'"
  UniqueName=:1.176
  MESSAGE "s" {
          STRING "No such object path '/core/ubuntu/media/Service/sessions/0'";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=25
  Sender=:1.175  Destination=core.ubuntu.media.Service  Path=/core/ubuntu/media/Service/sessions/0  Interface=org.mpris.MediaPlayer2.Player  Member=OpenUri
  UniqueName=:1.175
  MESSAGE "s" {
          STRING "file:///home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audiopFCsjq.ogg";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=52  ReplyCookie=25
  Sender=:1.176  Destination=:1.175
  ErrorName=org.freedesktop.DBus.Error.UnknownObject  ErrorMessage="No such object path '/core/ubuntu/media/Service/sessions/0'"
  UniqueName=:1.176
  MESSAGE "s" {
          STRING "No such object path '/core/ubuntu/media/Service/sessions/0'";
  };

```
PlayBack audio:
```
Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=151
  Sender=:1.175  Destination=core.ubuntu.media.Service  Path=/core/ubuntu/media/Service/sessions/0  Interface=org.mpris.MediaPlayer2.Player  Member=OpenUri
  UniqueName=:1.175
  MESSAGE "s" {
          STRING "file:///home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audiokhsKOl.ogg";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=178  ReplyCookie=151
  Sender=:1.176  Destination=:1.175
  ErrorName=org.freedesktop.DBus.Error.UnknownObject  ErrorMessage="No such object path '/core/ubuntu/media/Service/sessions/0'"
  UniqueName=:1.176
  MESSAGE "s" {
          STRING "No such object path '/core/ubuntu/media/Service/sessions/0'";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=152
  Sender=:1.175  Destination=core.ubuntu.media.Service  Path=/core/ubuntu/media/Service/sessions/0  Interface=org.freedesktop.DBus.Properties  Member=Get
  UniqueName=:1.175
  MESSAGE "ss" {
          STRING "org.mpris.MediaPlayer2.Player";
          STRING "IsAudioSource";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=179  ReplyCookie=152
  Sender=:1.176  Destination=:1.175
  ErrorName=org.freedesktop.DBus.Error.UnknownObject  ErrorMessage="No such object path '/core/ubuntu/media/Service/sessions/0'"
  UniqueName=:1.176
  MESSAGE "s" {
          STRING "No such object path '/core/ubuntu/media/Service/sessions/0'";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=153
  Sender=:1.175  Destination=core.ubuntu.media.Service  Path=/core/ubuntu/media/Service/sessions/0  Interface=org.freedesktop.DBus.Properties  Member=Get
  UniqueName=:1.175
  MESSAGE "ss" {
          STRING "org.mpris.MediaPlayer2.Player";
          STRING "Position";
  };
```

**Comment by mardy** [comment]
Thanks @lduboeuf , it's great that you found this issue before we merged this!

So, there are actually two issues

1) media-hub could not parse the apparmor label `messaging-app (enforce)` and crashed. I have a fix for this and I'll commit it soon.

2) but even once the above is fixed, the recorded media won't be played back, before for some reason the file is detected by gstreamer as a *video* file:
```
    80.741 - unknown:0 - parsed_uri.path: /home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audioauqrdE.ogg
    80.741 - unknown:0 - 
    80.742 - unknown:0 - Updating MPRIS TrackList properties:
    80.742 - unknown:0 - 	Tracks: 0
    80.743 - unknown:0 - 	has_previous: 0
    80.743 - unknown:0 - 	has_next: 0
    80.752 - unknown:0 - Found content type: video/3gpp
    80.752 - unknown:0 - Found video content
```

Inspecting the file from the terminal gives a similar result:
```
phablet@ubuntu-phablet:~$ file /home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audioauqrdE.ogg
/home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/audioauqrdE.ogg: ISO Media, MPEG v4 system, 3GPP
```

So I think I'll just hack around this and consider the mime type `video/3gpp` as audio.

**Comment by mardy** [comment]
> So, there are actually two issues
[...]

Both should be fixed now, please try the latest media-hub: https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fmedia-hub/detail/PR-28/30/artifacts/

**Comment by lduboeuf** [comment]
@mardy confirm it works with messaging app 👌

**Review by UniversalSuperBox — APPROVED** [review]
I've run the Canonical test plans and run many apps which test the sound system. I think we're ready to go.
